on:
  push:
  pull_request:

# on:
#   push:
#     tags:
#        - '*'

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2

      - run: python3 -m pip install pyoxidizer
      - run: pyoxidizer build install

      - name: Upload Distributions
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/x86_64-pc-windows-msvc/debug/install/
