on:
  push:
  pull_request:

# on:
#   push:
#     tags:
#        - '*'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install -U pip
          export PATH=~/.local/bin:$PATH
          pip3 install pyoxidizer
          pyoxidizer build install

      - name: Upload Distributions
        uses: actions/upload-artifact@v2
        with:
          name: app-linux
          path: build/x86_64-unknown-linux-gnu/debug/install/
